import type { SiteConfig } from '../types/content';

export const siteConfig: SiteConfig = {
  language: 'es',
  theme: 'system',
  dateStyle: 'short',
  accentColor: 'blue',
  showAbout: true,
  showExperience: true,
  showTerminal: true,
  showSystems: true,
  showProjects: true,
  showSkills: true,
  showEducation: true,
  showCertifications: true,
  showContact: true,
  cvPath: null, // Añade el PDF a public/cv/ y escribe '/cv/CV-Marcos-Gomez.pdf'.
};

export const siteText = {
  es: {
  portfolio: 'Portfolio personal',
  skipToContent: 'Ir al contenido',
  menu: 'Menú',
  closeMenu: 'Cerrar menú',
  backToTop: 'Volver al inicio',
  lightMode: 'Activar modo claro',
  darkMode: 'Activar modo oscuro',
  language: 'Idioma',
  current: 'Actualidad',
  currentlyAt: 'Actualmente en',
  viewProjects: 'Explorar proyectos',
  downloadCv: 'Descargar CV',
  contactCta: 'Hablemos',
  featured: 'Destacado',
  details: 'Ver detalles del proyecto',
  responsibilities: 'Mi contribución',
  concepts: 'Áreas de integración',
  github: 'GitHub',
  demo: 'Ver demo',
  credential: 'Ver credencial',
  connections: 'Conexiones',
  contactDescription: '¿Tienes un proyecto en mente? Podemos hablar de software, sistemas y de cómo hacer que funcionen mejor juntos.',
  footer: 'Software con propósito.',
  terminal: {
    title: 'portfolio — terminal',
    intro: 'Otra forma de conocer mi trabajo. Escribe help para ver los comandos.',
    input: 'Escribe un comando',
    submit: 'Ejecutar',
    unknown: 'Comando no reconocido. Escribe help.',
    empty: 'No hay contenido disponible.',
    prompt: 'visitor@portfolio:~$',
    help: {
      help: 'Ver los comandos disponibles',
      whoami: 'Perfil profesional',
      experience: 'Experiencia profesional',
      skills: 'Tecnologías y herramientas',
      projects: 'Proyectos visibles',
      education: 'Formación',
      clear: 'Limpiar la terminal',
    },
  },
  },
  en: {
    portfolio: 'Personal portfolio',
    skipToContent: 'Skip to content',
    menu: 'Menu',
    closeMenu: 'Close menu',
    backToTop: 'Back to top',
    lightMode: 'Switch to light mode',
    darkMode: 'Switch to dark mode',
    language: 'Language',
    current: 'Present',
    currentlyAt: 'Currently at',
    viewProjects: 'Explore projects',
    downloadCv: 'Download résumé',
    contactCta: "Let's talk",
    featured: 'Featured',
    details: 'View project details',
    responsibilities: 'My contribution',
    concepts: 'Integration areas',
    github: 'GitHub',
    demo: 'View demo',
    credential: 'View credential',
    connections: 'Connections',
    contactDescription: 'Have a project in mind? We can talk about software, systems, and how to make them work better together.',
    footer: 'Software with purpose.',
    terminal: {
      title: 'portfolio — terminal',
      intro: 'Another way to explore my work. Type help to see the commands.',
      input: 'Type a command',
      submit: 'Run',
      unknown: 'Command not found. Type help.',
      empty: 'No content available.',
      prompt: 'visitor@portfolio:~$',
      help: {
        help: 'Show available commands',
        whoami: 'Professional profile',
        experience: 'Professional experience',
        skills: 'Technologies and tools',
        projects: 'Visible projects',
        education: 'Education',
        clear: 'Clear the terminal',
      },
    },
  },
};
